---
label: Site Configuration
hide_body: true
display_field: logoText
fields:
- type: field_group
  name: metaData
  label: Meta Data
  fields:
  - type: text
    name: title
    label: Title
    config:
      required: true
  - type: text
    name: description
    label: Description
    config:
      required: true
  - type: text
    name: author
    label: Author
    config:
      required: true
  - type: text
    name: keyword
    label: Keyword
    config:
      required: true
  - type: file
    name: ogImage
    label: ogImage
- type: text
  name: baseURL
  label: Base URL
  config:
    required: true
- type: file
  name: logo
  label: Logo
- type: text
  name: logoText
  label: Logo Text
  config:
    required: true
- type: file
  name: favicon
  label: Favicon
- type: number
  name: postPerPage
  label: Posts Per Page
  config:
    required: true
    step: 1
    min: 1
- type: text
  name: copyright
  label: Copyright
pages:
- config/site.config.json
